// Code generated by mockery v2.9.4. DO NOT EDIT.

package arweave

import mock "github.com/stretchr/testify/mock"

// MockOption is an autogenerated mock type for the Option type
type MockOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockOption) Execute(_a0 *Arweave) *Arweave {
	ret := _m.Called(_a0)

	var r0 *Arweave
	if rf, ok := ret.Get(0).(func(*Arweave) *Arweave); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Arweave)
		}
	}

	return r0
}
